-- Central activity log table for ops/system monitoring.

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  level TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('debug', 'info', 'warn', 'error')),
  service TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'success',
  message TEXT NOT NULL,
  metadata JSONB,
  environment TEXT NOT NULL DEFAULT 'development',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_level_created_at ON public.activity_logs (level, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_service_created_at ON public.activity_logs (service, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs (user_id);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own activity logs" ON public.activity_logs;
CREATE POLICY "Users can insert own activity logs"
ON public.activity_logs
FOR INSERT
WITH CHECK ((user_id IS NULL) OR (user_id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own activity logs" ON public.activity_logs;
CREATE POLICY "Users can view own activity logs"
ON public.activity_logs
FOR SELECT
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Superadmins can view all activity logs" ON public.activity_logs;
CREATE POLICY "Superadmins can view all activity logs"
ON public.activity_logs
FOR SELECT
USING (public.is_superadmin());

DROP POLICY IF EXISTS "Superadmins can update activity logs" ON public.activity_logs;
CREATE POLICY "Superadmins can update activity logs"
ON public.activity_logs
FOR UPDATE
USING (public.is_superadmin())
WITH CHECK (public.is_superadmin());
